// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/buat-cv-home/BoldDark.tsx": () => import("../components/mockups/buat-cv-home/BoldDark.tsx"),
  "./components/mockups/buat-cv-home/Elegant.tsx": () => import("../components/mockups/buat-cv-home/Elegant.tsx"),
  "./components/mockups/buat-cv-home/Vibrant.tsx": () => import("../components/mockups/buat-cv-home/Vibrant.tsx")
};
